name       : gnome-2048
version    : 3.34.3
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-2048/3.34/gnome-2048-3.34.3.tar.xz : 8e87647ac14418aaae8998b759eba3c039ea0ba28e8cdd195e8fd46e925bedf0
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
