name       : gnome-2048
version    : 3.36.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-2048/3.36/gnome-2048-3.36.0.tar.xz : 1b790f145d0bd67a5339c16a70674807344ed11831e8c0245ed31956b4b38281
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
