name       : gnome-2048
version    : 3.38.2
release    : 16
source     :
    - git|https://gitlab.gnome.org/GNOME/libgnome-games-support.git : 406695a2bd14436cb7ff10001865db9d1c236fad
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
