name       : gnome-2048
version    : 3.34.2
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-2048/3.34/gnome-2048-3.34.2.tar.xz : e63534dab1271e4d608610037343911c9628e341c721247a483a1f96739e108c
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
