name       : gnome-2048
version    : 3.26.1
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-2048/3.26/gnome-2048-3.26.1.tar.xz : c10ca70a26365ceb93be8475758debe313f3db842046831cf2239ccdffa35035
license    : GPL-3.0
component  : games
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
