name       : gnome-2048
version    : 3.32.0
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-2048/3.32/gnome-2048-3.32.0.tar.xz : 3fa3d2efdb1f0d969570844411bc940b7a4f751cb7a2ab4870bee4b527e53121
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
