name       : gnome-2048
version    : 3.34.4
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-2048/3.34/gnome-2048-3.34.4.tar.xz : 1616b5fb88a16340bf9b96ee5474eb1efab3ff3dedd0c04e3738e39315f4c9ab
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
